### ISSUE TITLE
error al actualizar fichero

### ISSUE THREAD

**Issue by jfisbein** [jungla-team/enigma2_pre_start#1]
Con la ultima version del script da un error en la ultima funcion:

```
+ actualizar_fichero_junglescript
+ '[' '' -eq 1 ']'
./enigma2_pre_start.sh: line 130: [: : integer expression expected
```
se está comparando un string con un entero y como el string es vacio da un error.

**Comment by txolo99** [comment]
No tengo constancia de este error en ningún caso, y tiene que ser algo específico de tu deco. 
La única vía para que esa variable "CAMBIO" esté vacía es en la función **diferencias_fichero()**
Con lo cual me lleva a pensar que antes en tu log ha tenido que entrar por donde no existe DESTINO. El contenido de ese fichero es /usr/bin, ya que se establece como fija en el script. 

Por favor comprueba dos cosas:
1. Que existe la ruta /usr/bin en tu deco.
2. Ejecuta de nuevo y mándame el log, ya que ayer mismamente hubo actualización

**Comment by txolo99** [comment]
> 
> 
> Con la ultima version del script da un error en la ultima funcion:
> 
> ```
> + actualizar_fichero_junglescript
> + '[' '' -eq 1 ']'
> ./enigma2_pre_start.sh: line 130: [: : integer expression expected
> ```
> 
> se está comparando un string con un entero y como el string es vacio da un error.

No tengo constancia de este error en ningún caso, y tiene que ser algo específico de tu deco.
La única vía para que esa variable "CAMBIO" esté vacía es en la función diferencias_fichero()
Con lo cual me lleva a pensar que antes en tu log ha tenido que entrar por donde no existe DESTINO. El contenido de ese fichero es /usr/bin, ya que se establece como fija en el script.

Por favor comprueba dos cosas:
- Que existe la ruta /usr/bin en tu deco.
- Ejecuta de nuevo y mándame el log, ya que ayer mismamente hubo actualización

**Comment by jfisbein** [comment]
La carpeta `/usr/bin` si que existe en mi deco:
```
# ls -l /usr/
drwxr-xr-x    3 root     root         26416 Apr  2 16:10 bin
drwxr-xr-x    2 root     root           160 Feb 28 06:51 games
drwxr-xr-x   34 root     root          9968 Mar 25 14:14 include
drwxr-xr-x    2 root     root           160 May 18  2019 keys
drwxr-xr-x   18 root     root         22416 Apr  2 16:07 lib
drwxr-xr-x    2 root     root           328 Feb 29 19:13 libexec
drwxr-xr-x    3 root     root          7920 Apr  2 16:07 sbin
drwxr-xr-x    2 root     root           240 Mar  1 12:10 script
drwxr-xr-x   25 root     root          2488 Apr  2 16:07 share
drwxr-xr-x    3 root     root           224 Mar 25 14:14 src
```
Añado el log:

[enigma2_pre_start.log](https://github.com/jungla-team/enigma2_pre_start/files/4567587/enigma2_pre_start.log)

**Comment by txolo99** [comment]
> 
> 
> La carpeta `/usr/bin` si que existe en mi deco:
> 
> ```
> # ls -l /usr/
> drwxr-xr-x    3 root     root         26416 Apr  2 16:10 bin
> drwxr-xr-x    2 root     root           160 Feb 28 06:51 games
> drwxr-xr-x   34 root     root          9968 Mar 25 14:14 include
> drwxr-xr-x    2 root     root           160 May 18  2019 keys
> drwxr-xr-x   18 root     root         22416 Apr  2 16:07 lib
> drwxr-xr-x    2 root     root           328 Feb 29 19:13 libexec
> drwxr-xr-x    3 root     root          7920 Apr  2 16:07 sbin
> drwxr-xr-x    2 root     root           240 Mar  1 12:10 script
> drwxr-xr-x   25 root     root          2488 Apr  2 16:07 share
> drwxr-xr-x    3 root     root           224 Mar 25 14:14 src
> ```
> 
> Añado el log:
> 
> [enigma2_pre_start.log](https://github.com/jungla-team/enigma2_pre_start/files/4567587/enigma2_pre_start.log)

Ya sé lo que está pasando, la condición que no se está cumpliendo es:

> + '[' -f /usr/bin/enigma2_pre_start.sh ']'

Con lo cual no hace nada... y por eso la variable te la saca vacía. Comprueba que el propio fichero existe: ls -l /usr/bin/enigma2_pre_start.sh

Un salida normal de actualización del junglescript es así:

> + '[' -f /usr/bin/enigma2_pre_start.sh ']'
> + crear_dir_tmp
> + '[' '!' -d /tmp/junglescript ']'
> + echo 'no crea la carpeta temporal /tmp/junglescript'
> no crea la carpeta temporal /tmp/junglescript

**Comment by jfisbein** [comment]
Si, el problema era que no lo estaba ejecutando desde la carpeta `/usr/bin`.
Lo he movido y ya no sale ese error.
Gracias!
