### ISSUE TITLE
[MEJORA] Opción para situar favoritos TDT/IPTV guardados al principio de bouquets.tv

### ISSUE THREAD

**Issue by jrodzar** [jungla-team/enigma2_pre_start#2]
Hola gente,

Tengo amigos acostumbrados a tener los canales del TDT al principio de las listas, con "hidden markers" de relleno al final, de tal forma que empiezan entonces los de movistar en el 101.
¿Veríais posible/interesante poner algún parámetro en el fichero de configuración para indicar al script si debe de poner los favoritos conservados al final o al principio del fichero bouquets.tv?

Ya me diréis. Gracias!

**Comment by txolo99** [comment]
> Hola gente,
> 
> Tengo amigos acostumbrados a tener los canales del TDT al principio de las listas, con "hidden markers" de relleno al final, de tal forma que empiezan entonces los de movistar en el 101.
> ¿Veríais posible/interesante poner algún parámetro en el fichero de configuración para indicar al script si debe de poner los favoritos conservados al final o al principio del fichero bouquets.tv?
> 
> Ya me diréis. Gracias!

Valoramos tu aportación y si podemos la implementaremos en futuras versiones.
