### ISSUE TITLE
Vu+ zero

### ISSUE THREAD

**Issue by danilp** [jungla-team/enigma2_pre_start#3]
Hola, he probado varias veces instalar el script y el autosonic pero no hay manera que instale la lista de canales y picons en un vu+ zero V2. En cambio en mi zgemma h9.2s lo hace sin problema....

**Comment by PachisPachis** [comment]
Tengo un clon de VU+ Solo, con una versión antigua de OpenPLI 4.0. Tuve que instalar las librerias popt por ssh para que funcionase el script:

opkg install popt

**Comment by danilp** [comment]
Ok, gracias! Parece que con la nueva versión de autosonic va perfecto!
